# Generated by Django 4.0.3 on 2022-03-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license_checker', '0002_license_amount_license_license_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ('-created',)},
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64)),
                ('checks', models.IntegerField(default=0)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='license_checker.license')),
            ],
        ),
    ]
