# Generated by Django 4.0.3 on 2022-03-11 10:50

from django.db import migrations, models
import license_checker.common


class Migration(migrations.Migration):

    dependencies = [
        ('license_checker', '0004_domain_created_domain_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default=license_checker.common.generate_api_key, max_length=256)),
                ('app_name', models.CharField(max_length=40)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
