# Generated by Django 4.0.3 on 2022-03-11 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license_checker', '0005_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='license_checker.app'),
            preserve_default=False,
        ),
    ]
