# Generated by Django 4.0.6 on 2022-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_checker', '0006_license_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='envato_app_id',
            field=models.CharField(default=33971483, max_length=40),
            preserve_default=False,
        ),
    ]
