# Generated by Django 4.0.6 on 2022-08-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_checker', '0007_app_envato_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='force',
            field=models.BooleanField(blank=True, default=False, help_text='Override Envato license info!'),
        ),
        migrations.AlterField(
            model_name='app',
            name='envato_app_id',
            field=models.CharField(max_length=40, verbose_name='Envato App ID'),
        ),
    ]
